apiVersion: apps/v1
kind: Deployment
metadata:
  name: javaapp
  namespace: prod-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: javaapp
  template:
    metadata:
      labels:
        app: javaapp
    spec:
      containers:
      - name: appcontainer
        image: 285065163560.dkr.ecr.us-east-2.amazonaws.com/apprepo:1.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        ports:
        - containerPort: 8080
        env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: MYSQL_DATABASE
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: DB_PASSWORD
                
        startupProbe:
          httpGet:
            path: /
            port: 8080
          failureThreshold: 30      # 30 attempts * 5s = 150s startup window allowed
          periodSeconds: 5
        
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 10
          timeoutSeconds: 3

        readinessProbe:
          httpGet:
            path: /
            port: 8080
          periodSeconds: 5
          timeoutSeconds: 3