apiVersion: v1
kind: Service
metadata:
  name: javaapp
  namespace: prod-namespace
spec:
  type: LoadBalancer
  selector:
    app: javaapp
  ports:
  - port: 1101
    targetPort: 8080
    nodePort: 31999
